// ============================================================
// NIKATO — types/database.types.ts
// Auto-generated by: npx supabase gen types typescript --project-id YOUR_ID
// Manually stubbed here so TypeScript compiles before generation.
// Replace this entire file with the output of the CLI command above.
// ============================================================

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          phone: string;
          full_name: string;
          email: string | null;
          avatar_url: string | null;
          role: string;
          is_active: boolean;
          fcm_token: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      addresses: {
        Row: {
          id: string;
          user_id: string;
          label: string;
          address_line: string;
          city: string;
          pincode: string;
          lat: number;
          lng: number;
          is_default: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['addresses']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['addresses']['Insert']>;
      };
      shops: {
        Row: {
          id: string;
          owner_id: string;
          name: string;
          description: string | null;
          logo_url: string | null;
          phone: string;
          address_line: string;
          city: string;
          pincode: string;
          lat: number;
          lng: number;
          delivery_radius_km: number;
          is_open: boolean;
          is_delivery_available: boolean;
          min_order_amount: number;
          avg_delivery_minutes: number;
          commission_rate: number;
          is_approved: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['shops']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['shops']['Insert']>;
      };
      categories: {
        Row: {
          id: string;
          shop_id: string;
          name: string;
          sort_order: number;
          is_active: boolean;
        };
        Insert: Omit<Database['public']['Tables']['categories']['Row'], 'id'>;
        Update: Partial<Database['public']['Tables']['categories']['Insert']>;
      };
      products: {
        Row: {
          id: string;
          shop_id: string;
          category_id: string | null;
          name: string;
          description: string | null;
          image_url: string | null;
          price: number;
          mrp: number | null;
          stock: number;
          unit: string;
          is_available: boolean;
          is_veg: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['products']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['products']['Insert']>;
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          customer_id: string;
          shop_id: string;
          delivery_partner_id: string | null;
          delivery_address_id: string;
          status: string;
          payment_method: string;
          payment_status: string;
          subtotal: number;
          delivery_fee: number;
          discount: number;
          total_amount: number;
          commission_amount: number;
          shop_earning: number;
          delivery_earning: number;
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          special_instructions: string | null;
          cancelled_reason: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['orders']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string;
          quantity: number;
          unit_price: number;
          total_price: number;
          product_name: string;
          product_image: string | null;
        };
        Insert: Omit<Database['public']['Tables']['order_items']['Row'], 'id'>;
        Update: Partial<Database['public']['Tables']['order_items']['Insert']>;
      };
      delivery_locations: {
        Row: {
          id: string;
          delivery_partner_id: string;
          lat: number;
          lng: number;
          is_online: boolean;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['delivery_locations']['Row'], 'id'>;
        Update: Partial<Database['public']['Tables']['delivery_locations']['Insert']>;
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          body: string;
          type: string;
          data: Json | null;
          is_read: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['notifications']['Insert']>;
      };
      payments: {
        Row: {
          id: string;
          order_id: string;
          razorpay_order_id: string;
          razorpay_payment_id: string | null;
          razorpay_signature: string | null;
          amount: number;
          currency: string;
          status: string;
          gateway_response: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['payments']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['payments']['Insert']>;
      };
      commissions: {
        Row: {
          id: string;
          shop_id: string;
          order_id: string;
          rate: number;
          amount: number;
          settled: boolean;
          settled_at: string | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['commissions']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['commissions']['Insert']>;
      };
      shop_analytics: {
        Row: {
          id: string;
          shop_id: string;
          date: string;
          orders_count: number;
          revenue: number;
          cancelled: number;
        };
        Insert: Omit<Database['public']['Tables']['shop_analytics']['Row'], 'id'>;
        Update: Partial<Database['public']['Tables']['shop_analytics']['Insert']>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
